### ISSUE TITLE
downloading error

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#151] opened 2021-09-24 11:33 UTC
I tried to download this dataset: https://data.coat.no/dataset/v_heath_shrub_height_observational by clicking the zip-button on the web-page. I got one file with very cryptic text. version 2 has the same problem. version 1 downloads fine. This happened when I was logged in.

**Comment by frafra** [comment] 2022-08-15 08:54
I am cleaning up the issues.
I am closing this one, as this is a duplicate of #156.

**Closed by frafra** 2022-08-15 08:54 UTC
