### ISSUE TITLE
filename extension needed in ressource file name

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#47] opened 2019-11-08 15:42 UTC
It seems to be necessary to add the correct filename extension to the ressource filename. Otherwise the file format is not recognized when downloading the files. It is still possible to open txt-files, but it might cause problems With other formats such as images. So it might be good if the filename extension will be added automatically in case it is missing in order to avoid problems when downloading data.

**Comment by frafra** [comment] 2019-11-08 17:14
I would say that is a duplicate of #36. Feel free to reopen otherwise.

**Closed by frafra** 2019-11-08 17:14 UTC
