### ISSUE TITLE
Wrong DOI credentials (was: Error in bulk upload)

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#119] opened 2020-10-29 08:03 UTC
When using the bulk upload, the following error occurs after selecting the files: Error - internal server error

**Comment by frafra** [comment] 2020-11-06 12:06
Duplicate of #117.

**Comment by hannaboe** [comment] 2020-11-06 13:02
The bulk upload still doesn't work.

**Comment by frafra** [comment] 2020-11-06 13:51
I get a different error (not on the specific resource, which can happen due to DOI misconfiguration or duplicate name), but a gateway error, because the browser is waiting for too long if many files are added. I will create a new issue for that.

**Closed** 2020-11-06 13:50 UTC
Labels: duplicate
