### ISSUE TITLE
Problem with automatic completion of geographic locations

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#142] opened 2021-02-18 08:48 UTC
#130 is not completly fixed. 

The correct locations are added when creating a dataset. But when the metadata is changed later, the section 'Jakobselv' is still selected automatically if the location 'Vestre Jakobselv' is selected.

**Comment by mdlux** [comment] 2021-02-18 12:09
Ok, we will check

**Comment by frafra** [comment] 2021-06-17 12:38
You are right. Duplicate of #130.

**Closed by frafra** 2021-06-17 12:38 UTC
Labels: bug
