### ISSUE TITLE
How to find protocols related to a specific module?

### ISSUE THREAD

**Issue by eevasoininen** [COATnor/COAT_portal_issues#140] opened 2021-02-02 17:36 UTC
At the moment, if I go to the protocol-tab, I see the number of protocols related to each module. But when I click on a module name on the list under the map, all types of datasets of that module are visualised. 

I would like to be able to filter by module and dataset type (dataset, state variable, or protocol) at the same time. it seems that other kinds of filters (eg tags or localities) do function.

**Comment by mdlux** [comment] 2021-04-23 12:43
Clicking on a filter switches to the dataset TAB.

**Comment by frafra** [comment] 2021-06-17 11:54
Duplicate of #121.

**Closed by frafra** 2021-06-17 11:54 UTC
Labels: bug
