### ISSUE TITLE
Issues when downloading data files

### ISSUE THREAD

**Issue by hannaboe** [COATnor/COAT_portal_issues#160] opened 2022-04-01 13:42 UTC
There seems to be an inconsistency with downloading files from data.coat.no and the urls to the files.

I only checked a few datasets and found these issues:

**V_air_temperature_snowbed** is a public dataset, however the file-urls contain 'resource-under-embargo'. It's anyway possible to open the files in a new browser window by clicking on the download-button or to download the files with R.

**V_meadow_ground_cover_observational** has 3 versions. V1 is public, v2 and v3 are under embargo. V1 looks fine. In v2 and v3, the urls of the files from 2005 to 2018 (these are the public files) point to coatdemo.coat.no, The button for downloading is called 'Go to resource' instead of 'download'. It's possible to open the files in a new browser window or to download the files with R. The urls of the files from 2019 and 2020 (under embargo) look fine, but when opening or downloading them, they only contain strange signs.

**V_rodents_snaptrapping_individuals_regional** has 4 version. V1 is public and looks fine. All files of v1, v2 and v3 contain strange signs, except the file from 2021 in v4. All other urls in v4 contain 'resource-under-embargo'.

**Comment by frafra** [comment] 2022-04-11 17:50
"strange signs" -> it means that the synchronization went wrong, so these files needs to be copied over (see #156)

Wrong named resources: I need to investigate that, but it should be related with the bad sync mechanism we had. I could develop some kind of renaming tool to fix the existing ones if that is the case, while new resources should be fine.

**Comment by frafra** [comment] 2022-04-26 09:10
We could just try to drop the bad resources and upload them again, without recreating the dataset first, so we do not lose metadata.

**Comment by hannaboe** [comment] 2022-04-29 09:18
Can you let me know when you updated the official data portal and I can start uploading the datafiles again?

**Comment by frafra** [comment] 2022-04-29 10:43
Sure; it is going to happen very soon :)

**Comment by frafra** [comment] 2022-08-15 08:49
The demo portal has been updated and mostly usable. Data has been kept, but some changes require updating the datasets (like generating citations with the new format).
I am addressing the remaining issues that have been reported here, and release new updates in the next days. We should be ready by the end of the week.

**Comment by frafra** [comment] 2022-08-15 08:55
I am cleaning up the issues.
I am closing this one, as this is a duplicate of #156.

**Closed by frafra** 2022-08-15 08:55 UTC
