### ISSUE TITLE
All resources named as "resource under embargo" even if no embargo

### ISSUE THREAD

**Issue by mdlux** [COATnor/COAT_portal_issues#146] opened 2021-05-06 12:52 UTC
All the resources are named "resource under embargo" also when downloaded.

**Comment by frafra** [comment] 2021-06-07 12:13
Just some resources are named like that. I do not think there is a problem with the portal; I think the problem is due to the data synchronization mechanism.

**Comment by frafra** [comment] 2021-06-17 12:31
Duplicate of #132.

**Closed by frafra** 2021-06-17 12:31 UTC
Labels: bug
